server:
  port: 19999
  servlet:
    context-path: /nyxsservice
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200

# 数据源配置
spring:
  main:
    allow-circular-references: true
  # 配置数据源信息
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://150.158.50.73:3310/nyxs?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: liu3366998
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          druid:
            # 初始连接数
            initialSize: 10
            # 最小连接池数量
            minIdle: 20
            # 最大连接池数量
            maxActive: 50
            # 配置获取连接等待超时的时间
            maxWait: 60000
        slave_1:
          url:
          username:
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 150.158.50.73
    port: 6379
    password: 123456


# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ake.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  # 自动分页
  supportMethodsArguments: false
  params: count=countSql

# 日志配置
logging:
  file:
    name: /data/logs/sys-error.log
  config: classpath:logback-dev.xml
  level:
    com.ake: debug
    org.springframework: warn