server:
  port: 19999
  servlet:
    context-path: /nyxsservice
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200

# 数据源配置
spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: mysql-service # 默认数据源
      datasource:
        mysql-service:
          jdbc-url: jdbc:mysql://150.158.50.73:3310/nyxs?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: root
          password: liu3366998
          driver-class-name: com.mysql.cj.jdbc.Driver
        tdengine-service:
          # url: jdbc:TAOS-RS://150.158.50.73:6041/demo?charset=utf-8
          # driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
          url: jdbc:TAOS://150.158.50.73:6030/demo?charset=utf-8
          driver-class-name: com.taosdata.jdbc.TSDBDriver
          username: root
          password: taosdata
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      filters: stat,wall,log4j2



  redis:
    host: 150.158.50.73
    port: 6379
    password: 123456

# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.liu.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml



# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  # 自动分页
  supportMethodsArguments: false
  params: count=countSql

# 日志配置
logging:
  file:
    name: /data/logs/sys-error.log
  config: classpath:logback-dev.xml
  level:
    com.liu: debug
    org.springframework: warn